//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CONTRASTEntities : DbContext
    {
        public CONTRASTEntities()
            : base("name=CONTRASTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tb_m_arrange_cashallowance> tb_m_arrange_cashallowance { get; set; }
        public virtual DbSet<tb_m_category_lead_time> tb_m_category_lead_time { get; set; }
        public virtual DbSet<tb_m_destination> tb_m_destination { get; set; }
        public virtual DbSet<tb_m_divison_mapping> tb_m_divison_mapping { get; set; }
        public virtual DbSet<tb_m_employee> tb_m_employee { get; set; }
        public virtual DbSet<tb_m_flag_meaning> tb_m_flag_meaning { get; set; }
        public virtual DbSet<tb_m_gl_account> tb_m_gl_account { get; set; }
        public virtual DbSet<tb_m_lt_employee> tb_m_lt_employee { get; set; }
        public virtual DbSet<tb_m_lt_spec_employee> tb_m_lt_spec_employee { get; set; }
        public virtual DbSet<tb_m_multiple_dest_flag> tb_m_multiple_dest_flag { get; set; }
        public virtual DbSet<tb_m_overseas_allowance> tb_m_overseas_allowance { get; set; }
        public virtual DbSet<tb_m_overseas_flag> tb_m_overseas_flag { get; set; }
        public virtual DbSet<tb_m_participant_flag> tb_m_participant_flag { get; set; }
        public virtual DbSet<tb_m_purpose> tb_m_purpose { get; set; }
        public virtual DbSet<tb_m_rate_flight> tb_m_rate_flight { get; set; }
        public virtual DbSet<tb_m_rate_hotel> tb_m_rate_hotel { get; set; }
        public virtual DbSet<tb_m_rate_passport> tb_m_rate_passport { get; set; }
        public virtual DbSet<tb_m_rate_visa> tb_m_rate_visa { get; set; }
        public virtual DbSet<tb_m_region> tb_m_region { get; set; }
        public virtual DbSet<tb_m_request_type> tb_m_request_type { get; set; }
        public virtual DbSet<tb_m_tax> tb_m_tax { get; set; }
        public virtual DbSet<tb_m_transaction_mapping> tb_m_transaction_mapping { get; set; }
        public virtual DbSet<tb_m_travel_activity> tb_m_travel_activity { get; set; }
        public virtual DbSet<tb_m_travel_procedures> tb_m_travel_procedures { get; set; }
        public virtual DbSet<tb_m_vendor> tb_m_vendor { get; set; }
        public virtual DbSet<tb_m_winter_period> tb_m_winter_period { get; set; }
        public virtual DbSet<tb_r_travel_actualcost_BACKUP> tb_r_travel_actualcost_BACKUP { get; set; }
        public virtual DbSet<tb_r_travel_actualcost_BACKUP_DATA> tb_r_travel_actualcost_BACKUP_DATA { get; set; }
        public virtual DbSet<tb_r_travel_dit> tb_r_travel_dit { get; set; }
        public virtual DbSet<tb_r_travel_execution> tb_r_travel_execution { get; set; }
        public virtual DbSet<tb_r_travel_payment_verification> tb_r_travel_payment_verification { get; set; }
        public virtual DbSet<tb_r_travel_request_BACKUP> tb_r_travel_request_BACKUP { get; set; }
        public virtual DbSet<tb_r_travel_request_BACKUP_DATA> tb_r_travel_request_BACKUP_DATA { get; set; }
        public virtual DbSet<tb_r_travel_request_participant> tb_r_travel_request_participant { get; set; }
        public virtual DbSet<tb_r_travel_settlement> tb_r_travel_settlement { get; set; }
        public virtual DbSet<tb_r_travel_settlement_receipt> tb_r_travel_settlement_receipt { get; set; }
        public virtual DbSet<tb_bms_budget> tb_bms_budget { get; set; }
        public virtual DbSet<tb_m_div_approval_mapping> tb_m_div_approval_mapping { get; set; }
        public virtual DbSet<tb_m_mapping_approval> tb_m_mapping_approval { get; set; }
        public virtual DbSet<tb_m_verifier_employee> tb_m_verifier_employee { get; set; }
        public virtual DbSet<tb_r_travel_fixedcost_allowance> tb_r_travel_fixedcost_allowance { get; set; }
        public virtual DbSet<tb_test_div_map> tb_test_div_map { get; set; }
        public virtual DbSet<vw_employee_display_name> vw_employee_display_name { get; set; }
        public virtual DbSet<vw_lt_performance> vw_lt_performance { get; set; }
        public virtual DbSet<vw_request_summary> vw_request_summary { get; set; }
        public virtual DbSet<vw_send_email_notif_participant> vw_send_email_notif_participant { get; set; }
        public virtual DbSet<vw_send_email_notif_settlement> vw_send_email_notif_settlement { get; set; }
        public virtual DbSet<vw_send_email_trv_confirmation> vw_send_email_trv_confirmation { get; set; }
        public virtual DbSet<vw_sum_actualcost_dtl> vw_sum_actualcost_dtl { get; set; }
        public virtual DbSet<vw_sum_actualcost_dtl_gen_file> vw_sum_actualcost_dtl_gen_file { get; set; }
        public virtual DbSet<vw_sum_actualcost_hdr_gen_file> vw_sum_actualcost_hdr_gen_file { get; set; }
        public virtual DbSet<vw_summary_settlement> vw_summary_settlement { get; set; }
        public virtual DbSet<vw_travel_allowance> vw_travel_allowance { get; set; }
        public virtual DbSet<vw_travel_cost> vw_travel_cost { get; set; }
        public virtual DbSet<vw_travel_for_settlement> vw_travel_for_settlement { get; set; }
        public virtual DbSet<vw_travel_profile> vw_travel_profile { get; set; }
        public virtual DbSet<tb_m_mstr_user> tb_m_mstr_user { get; set; }
        public virtual DbSet<tb_m_vendor_employee> tb_m_vendor_employee { get; set; }
        public virtual DbSet<vw_travel_execution_list> vw_travel_execution_list { get; set; }
        public virtual DbSet<tb_m_budget> tb_m_budget { get; set; }
        public virtual DbSet<tb_m_budget_division_mapping> tb_m_budget_division_mapping { get; set; }
        public virtual DbSet<tb_m_employee_source_data> tb_m_employee_source_data { get; set; }
        public virtual DbSet<vw_BPD_verified> vw_BPD_verified { get; set; }
        public virtual DbSet<vw_settlement_verified> vw_settlement_verified { get; set; }
        public virtual DbSet<tb_m_budget_div_mapping> tb_m_budget_div_mapping { get; set; }
        public virtual DbSet<tb_r_record_rejected_verification> tb_r_record_rejected_verification { get; set; }
        public virtual DbSet<vw_rejected_travel_for_settlement> vw_rejected_travel_for_settlement { get; set; }
        public virtual DbSet<vw_tracking_transaction_data> vw_tracking_transaction_data { get; set; }
        public virtual DbSet<vw_total_budget> vw_total_budget { get; set; }
        public virtual DbSet<tb_r_record_generate_file> tb_r_record_generate_file { get; set; }
        public virtual DbSet<tb_m_photo_employee> tb_m_photo_employee { get; set; }
        public virtual DbSet<tb_m_budget_source_data> tb_m_budget_source_data { get; set; }
        public virtual DbSet<tb_m_employee_structure_organization> tb_m_employee_structure_organization { get; set; }
        public virtual DbSet<vw_invoice_actualcost> vw_invoice_actualcost { get; set; }
        public virtual DbSet<vw_actualcost_preparation> vw_actualcost_preparation { get; set; }
        public virtual DbSet<vw_actualCost_verified> vw_actualCost_verified { get; set; }
        public virtual DbSet<vw_rejected_actualcost_verification> vw_rejected_actualcost_verification { get; set; }
        public virtual DbSet<vw_invoice_actualcost_new> vw_invoice_actualcost_new { get; set; }
        public virtual DbSet<tb_r_travel_request> tb_r_travel_request { get; set; }
        public virtual DbSet<tb_r_travel_actualcost> tb_r_travel_actualcost { get; set; }
        public virtual DbSet<vw_actualcost_generate_file> vw_actualcost_generate_file { get; set; }
        public virtual DbSet<tb_r_statusUploadMaster> tb_r_statusUploadMaster { get; set; }
        public virtual DbSet<vw_payment_proposal> vw_payment_proposal { get; set; }
        public virtual DbSet<tb_m_special_employee> tb_m_special_employee { get; set; }
        public virtual DbSet<tb_r_invoice_actualcost> tb_r_invoice_actualcost { get; set; }
        public virtual DbSet<tb_r_record_payment_list> tb_r_record_payment_list { get; set; }
        public virtual DbSet<tb_r_record_payment_proposal> tb_r_record_payment_proposal { get; set; }
        public virtual DbSet<tb_r_travel_request_comment> tb_r_travel_request_comment { get; set; }
        public virtual DbSet<vw_payment_list> vw_payment_list { get; set; }
        public virtual DbSet<tb_m_special_employee_new> tb_m_special_employee_new { get; set; }
        public virtual DbSet<vw_tracking_transaction_data_new> vw_tracking_transaction_data_new { get; set; }
        public virtual DbSet<tb_r_record_settlement_receipt> tb_r_record_settlement_receipt { get; set; }
    }
}
