//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_bms_budget
    {
        public Nullable<short> fiscal_year { get; set; }
        public string eoa_no { get; set; }
        public string eoa_item_new { get; set; }
        public string wbs_no_new { get; set; }
        public string eoa_wbs_no { get; set; }
        public string eoa_wbs_description { get; set; }
        public string travel_type { get; set; }
        public Nullable<double> available_amount { get; set; }
        public Nullable<double> amount_new { get; set; }
        public string available_status { get; set; }
        public Nullable<double> initial_budget { get; set; }
        public Nullable<double> budget_remining { get; set; }
        public string reduction_option { get; set; }
        public string bod_date { get; set; }
        public string unit_code { get; set; }
        public string flag_budget { get; set; }
        public string status_budget { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> insert_date_bms { get; set; }
        public Nullable<System.DateTime> update_date_bms { get; set; }
    }
}
