//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_budget_source_data
    {
        public int id_budget { get; set; }
        public string Division { get; set; }
        public string Employee_Position { get; set; }
        public string Employee_Name { get; set; }
        public string Department { get; set; }
        public string Description { get; set; }
        public string Travel_Type { get; set; }
        public string Cost_Center { get; set; }
        public string WBS_Element { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> user_created { get; set; }
        public Nullable<bool> active_flag { get; set; }
    }
}
