//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_transaction_mapping
    {
        public int id_trans_mapping { get; set; }
        public Nullable<int> id_transaction { get; set; }
        public string jenis_transaksi { get; set; }
        public string information_actualcost { get; set; }
        public string description_mapping { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> active_flag { get; set; }
    }
}
