//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_category_lead_time
    {
        public int id_category_lead_time { get; set; }
        public int lead_time { get; set; }
        public string category_lead_time { get; set; }
        public Nullable<int> ordering_lead_time { get; set; }
    }
}
