//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_employee_source_data
    {
        public int id_data_pegawai { get; set; }
        public Nullable<double> noreg { get; set; }
        public string Nama_pegawai { get; set; }
        public string kelas { get; set; }
        public string Divisi { get; set; }
        public string Departemen { get; set; }
        public string Seksi { get; set; }
        public string posisi { get; set; }
        public Nullable<double> kode_unit { get; set; }
        public Nullable<double> aktif { get; set; }
        public string user_created { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    }
}
