//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_special_employee
    {
        public int id_spec_emp { get; set; }
        public Nullable<int> id_data_pegawai { get; set; }
        public string no_reg { get; set; }
        public string name { get; set; }
        public string @class { get; set; }
        public string position { get; set; }
        public Nullable<int> unit_code_id { get; set; }
        public string unit_code_code { get; set; }
        public string unit_code_name { get; set; }
        public string Bank_Name { get; set; }
        public string account_number { get; set; }
        public string beneficiary_name { get; set; }
        public string Divisi { get; set; }
        public string Departemen { get; set; }
        public Nullable<int> apprv_lv_1_1 { get; set; }
        public Nullable<int> apprv_lv_1_2 { get; set; }
        public Nullable<int> apprv_lv_1_3 { get; set; }
        public Nullable<int> apprv_lv_1_4 { get; set; }
        public Nullable<int> apprv_lv_1_5 { get; set; }
        public Nullable<int> apprv_lv_2_1 { get; set; }
        public Nullable<int> apprv_lv_2_2 { get; set; }
        public Nullable<int> apprv_lv_2_3 { get; set; }
        public Nullable<int> apprv_lv_2_4 { get; set; }
        public Nullable<int> apprv_lv_2_5 { get; set; }
        public Nullable<int> apprv_lv_3_1 { get; set; }
        public Nullable<int> apprv_lv_3_2 { get; set; }
        public Nullable<int> apprv_lv_3_3 { get; set; }
        public Nullable<int> apprv_lv_3_4 { get; set; }
        public Nullable<int> apprv_lv_3_5 { get; set; }
        public Nullable<int> apprv_lv_4_1 { get; set; }
        public Nullable<int> apprv_lv_4_2 { get; set; }
        public Nullable<int> apprv_lv_4_3 { get; set; }
        public Nullable<int> apprv_lv_4_4 { get; set; }
        public Nullable<int> apprv_lv_4_5 { get; set; }
        public Nullable<int> apprv_lv_5_1 { get; set; }
        public Nullable<int> apprv_lv_5_2 { get; set; }
        public Nullable<int> apprv_lv_5_3 { get; set; }
        public Nullable<int> apprv_lv_5_4 { get; set; }
        public Nullable<int> apprv_lv_5_5 { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string user_created { get; set; }
        public Nullable<bool> active_flag { get; set; }
    }
}
