//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_vendor_employee
    {
        public int id_vendor_emp { get; set; }
        public Nullable<int> no_reg { get; set; }
        public string vendor_code_employee { get; set; }
        public string bank_number { get; set; }
        public string bank_type { get; set; }
        public string Bank_Name { get; set; }
        public string account_number { get; set; }
        public string employee_name { get; set; }
        public string beneficiary_name { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string user_created { get; set; }
        public Nullable<bool> active_flag { get; set; }
    }
}
