//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_employee_structure_organization
    {
        public int id_structure_organization { get; set; }
        public string division { get; set; }
        public string division_head { get; set; }
        public string directorate { get; set; }
        public string directorate_head { get; set; }
        public string fd_local { get; set; }
        public string fd_japan { get; set; }
        public string vp { get; set; }
        public string pd { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> user_created { get; set; }
        public Nullable<bool> active_flag { get; set; }
        public string sub_directorate { get; set; }
        public string egm { get; set; }
    }
}
