//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_divison_mapping
    {
        public int id_division { get; set; }
        public string unit_code { get; set; }
        public string unit_name { get; set; }
        public string Abreviation { get; set; }
        public string level_code { get; set; }
        public string parent_unit { get; set; }
        public string unit_code_sap { get; set; }
        public Nullable<bool> inactive_flag { get; set; }
    }
}
