//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_vendor
    {
        public int id_vendor { get; set; }
        public string vendor_code { get; set; }
        public string vendor_name { get; set; }
        public string type { get; set; }
        public string bank_account { get; set; }
        public string account_holder { get; set; }
        public string name_of_bank { get; set; }
        public string swift_code { get; set; }
        public Nullable<int> skn { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string user_created { get; set; }
        public Nullable<bool> active_flag { get; set; }
    }
}
