//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_verifier_employee
    {
        public string code { get; set; }
        public string name { get; set; }
        public string @class { get; set; }
        public string position { get; set; }
        public string division_name { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<bool> active_flag { get; set; }
    }
}
