//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_budget_div_mapping
    {
        public int id_budget_mapping { get; set; }
        public Nullable<int> no_reg_employee { get; set; }
        public string division_employee { get; set; }
        public string division_budget { get; set; }
        public string posisi { get; set; }
        public Nullable<int> no_reg_budget { get; set; }
        public string department { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> user_created { get; set; }
        public Nullable<bool> active_flag { get; set; }
    }
}
