//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_photo_employee
    {
        public int photo_id { get; set; }
        public string code { get; set; }
        public string photo_emp { get; set; }
        public string status_photo { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
    }
}
