//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_overseas_allowance
    {
        public int id_allowance { get; set; }
        public string destination { get; set; }
        public string @class { get; set; }
        public string currency { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string user_created { get; set; }
        public Nullable<bool> active_flag { get; set; }
    }
}
