//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_mstr_user
    {
        public int id_user { get; set; }
        public string user_mstr { get; set; }
        public Nullable<int> no_reg { get; set; }
        public Nullable<int> unit_code { get; set; }
        public string position { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<bool> active_flag { get; set; }
    }
}
