//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_gl_account
    {
        public int id_gl_account { get; set; }
        public Nullable<bool> code_account { get; set; }
        public string desc_account { get; set; }
        public Nullable<int> gl_account { get; set; }
        public string information_account { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> active_flag { get; set; }
    }
}
