//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_special_employee_new
    {
        public int id_spec_emp { get; set; }
        public Nullable<int> id_data_pegawai { get; set; }
        public string no_reg { get; set; }
        public Nullable<int> apprv_lv_1_1 { get; set; }
        public Nullable<int> apprv_lv_1_2 { get; set; }
        public Nullable<int> apprv_lv_1_3 { get; set; }
        public Nullable<int> apprv_lv_1_4 { get; set; }
        public Nullable<int> apprv_lv_1_5 { get; set; }
        public Nullable<int> apprv_lv_2_1 { get; set; }
        public Nullable<int> apprv_lv_2_2 { get; set; }
        public Nullable<int> apprv_lv_2_3 { get; set; }
        public Nullable<int> apprv_lv_2_4 { get; set; }
        public Nullable<int> apprv_lv_2_5 { get; set; }
        public Nullable<int> apprv_lv_3_1 { get; set; }
        public Nullable<int> apprv_lv_3_2 { get; set; }
        public Nullable<int> apprv_lv_3_3 { get; set; }
        public Nullable<int> apprv_lv_3_4 { get; set; }
        public Nullable<int> apprv_lv_3_5 { get; set; }
        public Nullable<int> apprv_lv_4_1 { get; set; }
        public Nullable<int> apprv_lv_4_2 { get; set; }
        public Nullable<int> apprv_lv_4_3 { get; set; }
        public Nullable<int> apprv_lv_4_4 { get; set; }
        public Nullable<int> apprv_lv_4_5 { get; set; }
        public Nullable<int> apprv_lv_5_1 { get; set; }
        public Nullable<int> apprv_lv_5_2 { get; set; }
        public Nullable<int> apprv_lv_5_3 { get; set; }
        public Nullable<int> apprv_lv_5_4 { get; set; }
        public Nullable<int> apprv_lv_5_5 { get; set; }
        public Nullable<int> apprv_lv_6_1 { get; set; }
        public Nullable<int> apprv_lv_6_2 { get; set; }
        public Nullable<int> apprv_lv_6_3 { get; set; }
        public Nullable<int> apprv_lv_6_4 { get; set; }
        public Nullable<int> apprv_lv_6_5 { get; set; }
        public Nullable<int> apprv_lv_7_1 { get; set; }
        public Nullable<int> apprv_lv_7_2 { get; set; }
        public Nullable<int> apprv_lv_7_3 { get; set; }
        public Nullable<int> apprv_lv_7_4 { get; set; }
        public Nullable<int> apprv_lv_7_5 { get; set; }
        public string additional1 { get; set; }
        public string additional2 { get; set; }
        public string additional3 { get; set; }
        public string additional4 { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> user_created { get; set; }
        public Nullable<bool> active_flag { get; set; }
    }
}
