//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_travel_procedures
    {
        public int id_travel_procedures { get; set; }
        public string @class { get; set; }
        public string destination_type { get; set; }
        public Nullable<short> id_region { get; set; }
        public string apprv_by_lvl1 { get; set; }
        public string apprv_by_lvl2 { get; set; }
        public string apprv_by_lvl3 { get; set; }
        public string apprv_by_lvl4 { get; set; }
        public string apprv_by_lvl5 { get; set; }
        public string extend_day { get; set; }
        public string reduction_day { get; set; }
        public string destination_revision { get; set; }
        public string member_revision { get; set; }
        public string diversion_approval_dh { get; set; }
        public string lt_submission { get; set; }
        public string lt_submission_visa { get; set; }
        public string flight_standard_allowance { get; set; }
        public string upgrade_class_req { get; set; }
        public string flight_reservation_lt { get; set; }
        public string issued_ticket_lt { get; set; }
        public string issued_ticket_req_doc { get; set; }
        public string airlines_priority { get; set; }
        public string airlines_option { get; set; }
        public string hotel_standard_allowance { get; set; }
        public string upgrade_star_hotel { get; set; }
        public string room_type { get; set; }
        public string hotel_reservation_lt { get; set; }
        public string issued_hotel_req_doc { get; set; }
        public Nullable<double> meal_allowance { get; set; }
        public Nullable<double> deduction { get; set; }
        public Nullable<double> pre_allowance_1_to_14_day { get; set; }
        public Nullable<double> pre_allowance_15_to_90_day { get; set; }
        public Nullable<double> pre_allowance_90_more { get; set; }
        public Nullable<double> extra_dep_arr { get; set; }
        public Nullable<double> extra_weekend { get; set; }
        public Nullable<double> winter_allowance { get; set; }
        public string cash_lt_submission { get; set; }
        public string communication_allowance { get; set; }
        public string laundry_allowance { get; set; }
        public string land_transport { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string user_created { get; set; }
        public Nullable<bool> active_flag { get; set; }
        public string apprv_by_lvl6 { get; set; }
        public string apprv_by_lvl7 { get; set; }
        public string apprv_by_lvl8 { get; set; }
        public string apprv_by_lvl9 { get; set; }
        public string apprv_by_lvl10 { get; set; }
        public string apprv_by_lvl11 { get; set; }
        public string apprv_by_lvl12 { get; set; }
        public string apprv_by_lvl13 { get; set; }
        public string apprv_by_lvl14 { get; set; }
        public string apprv_by_lvl15 { get; set; }
        public string apprv_by_lvl16 { get; set; }
        public string apprv_by_lvl17 { get; set; }
        public string apprv_by_lvl18 { get; set; }
        public string apprv_by_lvl19 { get; set; }
        public string apprv_by_lvl20 { get; set; }
    }
}
