//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_flag_meaning
    {
        public int id_meaning { get; set; }
        public string table_name { get; set; }
        public string field_name { get; set; }
        public string status_value { get; set; }
        public string meaning_status { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
