//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_m_div_approval_mapping
    {
        public int unit_code { get; set; }
        public Nullable<int> dh_code { get; set; }
        public Nullable<int> director { get; set; }
        public Nullable<int> local_fd { get; set; }
        public Nullable<int> japan_fd { get; set; }
        public Nullable<int> vp { get; set; }
        public Nullable<int> pd { get; set; }
        public Nullable<int> egm { get; set; }
        public Nullable<int> superior1 { get; set; }
        public Nullable<int> superior2 { get; set; }
        public Nullable<int> superior3 { get; set; }
        public Nullable<int> superior4 { get; set; }
        public Nullable<int> superior5 { get; set; }
        public Nullable<int> superior6 { get; set; }
        public Nullable<int> superior7 { get; set; }
        public Nullable<int> superior8 { get; set; }
        public Nullable<int> superior9 { get; set; }
        public Nullable<int> superior10 { get; set; }
        public Nullable<int> superior11 { get; set; }
        public Nullable<int> superior12 { get; set; }
        public Nullable<int> superior13 { get; set; }
    }
}
