//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_r_travel_settlement_receipt
    {
        public int id_receipt { get; set; }
        public int id_actualcost { get; set; }
        public string path_file { get; set; }
        public string user_created { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
