//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_r_record_settlement_receipt
    {
        public int id_receipt { get; set; }
        public string group_code { get; set; }
        public Nullable<int> no_reg { get; set; }
        public string destination1 { get; set; }
        public Nullable<System.DateTime> startDate1 { get; set; }
        public Nullable<System.DateTime> endDate1 { get; set; }
        public string destination2 { get; set; }
        public Nullable<System.DateTime> startDate2 { get; set; }
        public Nullable<System.DateTime> endDate2 { get; set; }
        public string destination3 { get; set; }
        public Nullable<System.DateTime> startDate3 { get; set; }
        public Nullable<System.DateTime> endDate3 { get; set; }
        public string destination4 { get; set; }
        public Nullable<System.DateTime> startDate4 { get; set; }
        public Nullable<System.DateTime> endDate4 { get; set; }
        public string destination5 { get; set; }
        public Nullable<System.DateTime> startDate5 { get; set; }
        public Nullable<System.DateTime> endDate5 { get; set; }
        public string destination6 { get; set; }
        public Nullable<System.DateTime> startDate6 { get; set; }
        public Nullable<System.DateTime> endDate6 { get; set; }
        public Nullable<System.DateTime> StartSettlement { get; set; }
        public Nullable<System.DateTime> EndSettlement { get; set; }
        public Nullable<double> actual_ticket { get; set; }
        public Nullable<double> actual_hotel { get; set; }
        public Nullable<int> actual_meal { get; set; }
        public Nullable<int> actual_transport { get; set; }
        public Nullable<int> actual_laundry { get; set; }
        public Nullable<int> actual_misc { get; set; }
        public Nullable<int> suspense_ticket { get; set; }
        public Nullable<int> suspense_hotel { get; set; }
        public Nullable<int> suspense_meal { get; set; }
        public Nullable<int> suspense_transport { get; set; }
        public Nullable<int> suspense_laundry { get; set; }
        public Nullable<int> suspense_misc { get; set; }
        public Nullable<double> grand_total { get; set; }
        public Nullable<int> user_created { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<bool> active_flag { get; set; }
    }
}
