//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_r_travel_actualcost_BACKUP
    {
        public int id_actualcost { get; set; }
        public string group_code { get; set; }
        public int no_reg { get; set; }
        public int id_request { get; set; }
        public string id_sqn { get; set; }
        public string jenis_transaksi { get; set; }
        public int amount { get; set; }
        public string tax { get; set; }
        public string vendor_code { get; set; }
        public string tax_invoice_number { get; set; }
        public string invoice_number { get; set; }
        public Nullable<int> amount_total { get; set; }
        public string wbs_no { get; set; }
        public string cost_center { get; set; }
        public Nullable<System.DateTime> start_date_extend { get; set; }
        public Nullable<System.DateTime> end_date_extend { get; set; }
        public string ap_verified_status { get; set; }
        public string ap_verified_by { get; set; }
        public Nullable<System.DateTime> ap_verified_datetime { get; set; }
        public string sh_verified_status { get; set; }
        public string sh_verified_by { get; set; }
        public Nullable<System.DateTime> sh_verified_datetime { get; set; }
        public string dph_verified_status { get; set; }
        public string dph_verified_by { get; set; }
        public Nullable<System.DateTime> dph_verified_datetime { get; set; }
        public string pac_status { get; set; }
        public string pac_insert_by { get; set; }
        public Nullable<System.DateTime> pac_insert_datetime { get; set; }
        public string ga_status { get; set; }
        public string ga_insert_by { get; set; }
        public Nullable<System.DateTime> ga_insert_datetime { get; set; }
        public string fd_status { get; set; }
        public string fd_insert_by { get; set; }
        public Nullable<System.DateTime> fd_insert_datetime { get; set; }
        public string dh_status { get; set; }
        public string dh_insert_by { get; set; }
        public Nullable<System.DateTime> dh_insert_datetime { get; set; }
        public string final_status { get; set; }
        public string information_actualcost { get; set; }
        public string user_created { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string path_file { get; set; }
    }
}
