//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_r_travel_execution
    {
        public int id_travel { get; set; }
        public string group_code { get; set; }
        public string pic_path { get; set; }
        public string desc_upload { get; set; }
        public Nullable<short> uploaded { get; set; }
        public Nullable<short> numbers { get; set; }
        public string signature_path { get; set; }
        public Nullable<System.DateTime> execution_date { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> latitude { get; set; }
        public string user_created { get; set; }
        public string status { get; set; }
    }
}
