//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_r_record_payment_list
    {
        public int id_record { get; set; }
        public string group_code { get; set; }
        public string item_no { get; set; }
        public Nullable<int> trans_type { get; set; }
        public string vendor_code { get; set; }
        public Nullable<System.DateTime> pv_date { get; set; }
        public string generate_by { get; set; }
        public Nullable<System.DateTime> generate_date { get; set; }
    }
}
