//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_r_invoice_actualcost
    {
        public int id_invoice { get; set; }
        public Nullable<int> id_data { get; set; }
        public string group_code { get; set; }
        public Nullable<int> vendor_code { get; set; }
        public string vendor_name { get; set; }
        public string bank_account { get; set; }
        public Nullable<int> no_reg { get; set; }
        public string name { get; set; }
        public string wbs_no { get; set; }
        public string cost_center { get; set; }
        public string qty { get; set; }
        public string invoice_number { get; set; }
        public string tax_invoice_number { get; set; }
        public Nullable<int> amount_total { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string employee_input { get; set; }
        public string jenis_transaksi { get; set; }
        public string destination_1 { get; set; }
        public Nullable<System.DateTime> startDate_1 { get; set; }
        public Nullable<System.DateTime> endDate_1 { get; set; }
        public string hotel_flight_name_1 { get; set; }
        public Nullable<int> Duration_1 { get; set; }
        public Nullable<int> amount_1 { get; set; }
        public string destination_2 { get; set; }
        public Nullable<System.DateTime> startDate_2 { get; set; }
        public Nullable<System.DateTime> endDate_2 { get; set; }
        public string hotel_flight_name_2 { get; set; }
        public Nullable<int> Duration_2 { get; set; }
        public Nullable<int> amount_2 { get; set; }
        public string destination_3 { get; set; }
        public Nullable<System.DateTime> startDate_3 { get; set; }
        public Nullable<System.DateTime> endDate_3 { get; set; }
        public string hotel_flight_name_3 { get; set; }
        public Nullable<int> Duration_3 { get; set; }
        public Nullable<int> amount_3 { get; set; }
        public string destination_4 { get; set; }
        public Nullable<System.DateTime> startDate_4 { get; set; }
        public Nullable<System.DateTime> endDate_4 { get; set; }
        public string hotel_flight_name_4 { get; set; }
        public Nullable<int> Duration_4 { get; set; }
        public Nullable<int> amount_4 { get; set; }
        public string destination_5 { get; set; }
        public Nullable<System.DateTime> startDate_5 { get; set; }
        public Nullable<System.DateTime> endDate_5 { get; set; }
        public string hotel_flight_name_5 { get; set; }
        public Nullable<int> Duration_5 { get; set; }
        public Nullable<int> amount_5 { get; set; }
        public string destination_6 { get; set; }
        public Nullable<System.DateTime> startDate_6 { get; set; }
        public Nullable<System.DateTime> endDate_6 { get; set; }
        public string hotel_flight_name_6 { get; set; }
        public Nullable<int> Duration_6 { get; set; }
        public Nullable<int> amount_6 { get; set; }
        public string PO_issued_by { get; set; }
        public Nullable<int> PO_issued_flag { get; set; }
        public Nullable<System.DateTime> PO_issued_date { get; set; }
        public string GR_issued_by { get; set; }
        public Nullable<int> GR_issued_flag { get; set; }
        public Nullable<System.DateTime> GR_issued_date { get; set; }
    }
}
