//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_r_travel_dit
    {
        public int id_dit { get; set; }
        public Nullable<int> no_reg { get; set; }
        public Nullable<int> travel_month { get; set; }
        public Nullable<int> periode { get; set; }
        public Nullable<int> room_night { get; set; }
        public Nullable<int> id_destination_city { get; set; }
        public string destination_city { get; set; }
        public string destination_code { get; set; }
        public Nullable<bool> overseas_flag { get; set; }
        public string travel_purpose { get; set; }
        public Nullable<double> transit_by_land { get; set; }
        public Nullable<double> transit_by_air { get; set; }
        public Nullable<double> total_transit { get; set; }
        public Nullable<double> allowance_meal_idr { get; set; }
        public Nullable<int> allowance_preparation { get; set; }
        public Nullable<int> allowance_winter { get; set; }
        public Nullable<double> allowance_hotel { get; set; }
        public Nullable<double> allowance_transportation { get; set; }
        public Nullable<double> allowance_laundry { get; set; }
        public Nullable<double> allowance_miscellaneous { get; set; }
        public Nullable<double> allowance_total_basic { get; set; }
        public Nullable<double> allowance_ticket { get; set; }
        public Nullable<double> allowance_visa { get; set; }
        public Nullable<double> allowance_passport { get; set; }
        public Nullable<double> allowance_total_document { get; set; }
        public Nullable<double> allowance_grand_total { get; set; }
        public string apprv_dh { get; set; }
        public Nullable<int> apprv_by { get; set; }
        public Nullable<System.DateTime> apprv_date { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string user_created { get; set; }
        public string comments { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<bool> active_flag { get; set; }
    }
}
