//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_r_record_rejected_verification
    {
        public int id_reject { get; set; }
        public Nullable<int> id_actualcost { get; set; }
        public string comment { get; set; }
        public string process_reject { get; set; }
        public Nullable<int> user_created { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    }
}
