//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_r_travel_request_participant
    {
        public int id_request_participant { get; set; }
        public Nullable<int> no_reg_parent { get; set; }
        public string group_code { get; set; }
        public Nullable<int> no_reg { get; set; }
        public Nullable<double> allowance_idr { get; set; }
        public Nullable<double> allowance_usd { get; set; }
        public Nullable<double> allowance_jpy { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<int> user_modified { get; set; }
        public Nullable<bool> active_flag { get; set; }
    }
}
