//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_test_div_map
    {
        public int unit_code { get; set; }
        public Nullable<int> dh_code { get; set; }
        public Nullable<int> director { get; set; }
        public Nullable<int> local_fd { get; set; }
        public Nullable<int> japan_fd { get; set; }
        public Nullable<int> vp { get; set; }
        public Nullable<int> pd { get; set; }
    }
}
