//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_employee_display_name
    {
        public string no_reg { get; set; }
        public string name { get; set; }
        public string unit_code_name { get; set; }
        public string display_name { get; set; }
    }
}
