//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_lt_performance
    {
        public string group_code { get; set; }
        public string level_approval { get; set; }
        public Nullable<int> destination { get; set; }
        public Nullable<int> apprv_by { get; set; }
        public string unit_code_code { get; set; }
        public Nullable<System.DateTime> submit_date { get; set; }
        public Nullable<System.DateTime> target_date { get; set; }
        public Nullable<System.DateTime> apprv_date { get; set; }
        public Nullable<int> lead_time { get; set; }
        public string category { get; set; }
        public Nullable<int> ordering_category { get; set; }
    }
}
