//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_payment_list
    {
        public int id_data { get; set; }
        public Nullable<int> MANDT { get; set; }
        public string PV_NO { get; set; }
        public Nullable<int> PV_YEAR { get; set; }
        public Nullable<int> ITEM_NO { get; set; }
        public string PV_DATE { get; set; }
        public int PV_TYPE { get; set; }
        public Nullable<int> TRANS_TYPE { get; set; }
        public string VENDOR { get; set; }
        public int VENDOR_GRP { get; set; }
        public string INVOICE_NO { get; set; }
        public string TAX_NO { get; set; }
        public string PAYMENT_TERM { get; set; }
        public string PAYMENT_METHOD { get; set; }
        public string PLAN_PAYMENT_DT { get; set; }
        public Nullable<int> POSTING_DT { get; set; }
        public Nullable<int> TOTAL_AMOUNT { get; set; }
        public int DPP_AMOUNT { get; set; }
        public string CURRENCY { get; set; }
        public string TAX_CODE { get; set; }
        public string HEADER_TEXT { get; set; }
        public string BANK_TYPE { get; set; }
        public Nullable<int> gl_account { get; set; }
        public Nullable<int> AMOUNT { get; set; }
        public string COST_CENTER { get; set; }
        public string WBS_ELEMENT { get; set; }
        public string ITEM_TEXT { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> SAP_DOC_NO { get; set; }
        public Nullable<int> SAP_DOC_YEAR { get; set; }
        public string BTR_NO { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public string DESTINATION { get; set; }
        public Nullable<int> ID_CITY { get; set; }
        public string BUDGET { get; set; }
        public string TOTAL_AMOUNT_ { get; set; }
        public string COST_CENTER_ { get; set; }
        public string WBS_ELEMENT_ { get; set; }
        public string TRAVEL_TYPE { get; set; }
        public string BTR_DATE { get; set; }
        public string PLAN_PAYMENT_DATE { get; set; }
        public string PAYMENT_METHOD_ { get; set; }
    }
}
