//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_send_email_notif_settlement
    {
        public string group_code { get; set; }
        public int id_request { get; set; }
        public Nullable<int> no_reg { get; set; }
        public string name { get; set; }
        public Nullable<int> id_destination_city { get; set; }
        public string destination_name { get; set; }
        public Nullable<int> invited_by { get; set; }
        public string invited_by_name { get; set; }
        public Nullable<int> assign_by { get; set; }
        public string assign_by_name { get; set; }
        public string travel_purpose { get; set; }
        public string reason_of_assigment { get; set; }
        public Nullable<bool> overseas_flag { get; set; }
        public string overseas_desc { get; set; }
        public Nullable<bool> participants_flag { get; set; }
        public string participant_desc { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string mail { get; set; }
    }
}
