//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_send_email_trv_confirmation
    {
        public int id_dit { get; set; }
        public Nullable<int> no_reg { get; set; }
        public string name { get; set; }
        public Nullable<int> travel_month { get; set; }
        public Nullable<int> periode { get; set; }
        public Nullable<int> room_night { get; set; }
        public Nullable<int> id_destination_city { get; set; }
        public string destination_city { get; set; }
        public string destination_code { get; set; }
        public string region_name { get; set; }
        public Nullable<bool> overseas_flag { get; set; }
        public string overseas_desc { get; set; }
        public string travel_purpose { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> apprv_date { get; set; }
        public string mail { get; set; }
    }
}
