//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_summary_settlement
    {
        public string group_code { get; set; }
        public Nullable<int> no_reg { get; set; }
        public string emp_name { get; set; }
        public string destination_1 { get; set; }
        public Nullable<System.DateTime> startDate_1 { get; set; }
        public Nullable<System.DateTime> endDate_1 { get; set; }
        public string destination_2 { get; set; }
        public Nullable<System.DateTime> startDate_2 { get; set; }
        public Nullable<System.DateTime> endDate_2 { get; set; }
        public string destination_3 { get; set; }
        public Nullable<System.DateTime> startDate_3 { get; set; }
        public Nullable<System.DateTime> endDate_3 { get; set; }
        public string destination_4 { get; set; }
        public Nullable<System.DateTime> startDate_4 { get; set; }
        public Nullable<System.DateTime> endDate_4 { get; set; }
        public string destination_5 { get; set; }
        public Nullable<System.DateTime> startDate_5 { get; set; }
        public Nullable<System.DateTime> endDate_5 { get; set; }
        public string destination_6 { get; set; }
        public Nullable<System.DateTime> startDate_6 { get; set; }
        public Nullable<System.DateTime> endDate_6 { get; set; }
        public int total_ticket { get; set; }
        public int total_hotel { get; set; }
        public int total_meal { get; set; }
        public int total_winter { get; set; }
        public int total_preparation { get; set; }
        public int total_laundry { get; set; }
        public int total_miscellaneous { get; set; }
        public int total_transportation { get; set; }
        public Nullable<int> grand_total_settlement { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
    }
}
