//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_sum_actualcost_hdr_gen_file
    {
        public int MANDT { get; set; }
        public Nullable<int> CTSNO { get; set; }
        public string PV_NO { get; set; }
        public Nullable<int> PV_YEAR { get; set; }
        public int ITEM_NO { get; set; }
        public Nullable<System.DateTime> PV_DATE { get; set; }
        public string PV_TYPE { get; set; }
        public Nullable<int> PV_NO_SUSPENSE { get; set; }
        public Nullable<int> PV_YEAR_SUSPENSE { get; set; }
        public Nullable<int> TRANS_TYPE { get; set; }
        public string VENDOR { get; set; }
        public int VENDOR_GRP { get; set; }
        public string INVOICE_NO { get; set; }
        public string TAX_NO { get; set; }
        public string PAYMENT_TERM { get; set; }
        public string PAYMENT_METHOD { get; set; }
        public Nullable<System.DateTime> PLAN_PAYMENT_DT { get; set; }
        public Nullable<int> POSTING_DT { get; set; }
        public Nullable<int> TOTAL_AMOUNT { get; set; }
        public int DPP_AMOUNT { get; set; }
        public string CURRENCY { get; set; }
        public string TAX_CODE { get; set; }
        public string HEADER_TEXT { get; set; }
        public Nullable<int> BANK_TYPE { get; set; }
        public Nullable<int> FROM_CURR { get; set; }
        public Nullable<int> EXCHANGE_RATE { get; set; }
        public Nullable<int> EXRATE_SUSPENSE { get; set; }
        public Nullable<int> DIFF_EXRATE { get; set; }
        public Nullable<int> NO_SUSPENSE_FLAG { get; set; }
        public Nullable<int> COST_CENTER_FLAG { get; set; }
        public Nullable<int> TAX_ASSIGNMENT { get; set; }
        public Nullable<int> ACC_INF_ASSIGNMENT { get; set; }
        public Nullable<int> TAX_DT { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> SAP_DOC_NO { get; set; }
        public Nullable<int> SAP_DOC_YEAR { get; set; }
    }
}
