//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_sum_actualcost_dtl_gen_file
    {
        public string PV_NO { get; set; }
        public Nullable<int> PV_YEAR { get; set; }
        public Nullable<int> ITEM_NO { get; set; }
        public Nullable<int> GL_ACCOUNT { get; set; }
        public Nullable<int> AMOUNT { get; set; }
        public Nullable<int> COST_CENTER { get; set; }
        public Nullable<int> WBS_ELEMENT { get; set; }
        public string ITEM_TEXT { get; set; }
    }
}
