//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_travel_execution_list
    {
        public int id_data { get; set; }
        public Nullable<int> id_request { get; set; }
        public string group_code { get; set; }
        public Nullable<int> id_dit { get; set; }
        public Nullable<int> no_reg { get; set; }
        public Nullable<int> destination_code { get; set; }
        public Nullable<bool> multiple_destination_flag { get; set; }
        public string departure { get; set; }
        public Nullable<bool> participants_flag { get; set; }
        public Nullable<bool> overseas_flag { get; set; }
        public Nullable<bool> request_type { get; set; }
        public string travel_purpose { get; set; }
        public Nullable<int> invited_by { get; set; }
        public Nullable<int> assign_by { get; set; }
        public string reason_of_assigment { get; set; }
        public Nullable<bool> air_ticket_flag { get; set; }
        public Nullable<bool> passport_flag { get; set; }
        public Nullable<int> apprv_by_lvl1 { get; set; }
        public Nullable<int> apprv_by_lvl2 { get; set; }
        public Nullable<int> apprv_by_lvl3 { get; set; }
        public Nullable<int> apprv_by_lvl4 { get; set; }
        public Nullable<int> apprv_by_lvl5 { get; set; }
        public string apprv_flag_lvl1 { get; set; }
        public string apprv_flag_lvl2 { get; set; }
        public string apprv_flag_lvl3 { get; set; }
        public string apprv_flag_lvl4 { get; set; }
        public string apprv_flag_lvl5 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl1 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl2 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl3 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl4 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl5 { get; set; }
        public Nullable<double> budget { get; set; }
        public string remaining_budget { get; set; }
        public Nullable<bool> exep_empolyee { get; set; }
        public string comments { get; set; }
        public Nullable<double> transit_by_land { get; set; }
        public Nullable<double> transit_by_air { get; set; }
        public Nullable<double> total_transit { get; set; }
        public Nullable<double> allowance_transit_by_land { get; set; }
        public Nullable<double> allowance_transit_by_air { get; set; }
        public Nullable<double> total_allowance_transit { get; set; }
        public Nullable<double> allowance_meal_idr { get; set; }
        public Nullable<double> allowance_preparation { get; set; }
        public Nullable<double> allowance_winter { get; set; }
        public Nullable<double> allowance_hotel { get; set; }
        public Nullable<double> allowance_transportation { get; set; }
        public Nullable<double> allowance_laundry { get; set; }
        public Nullable<double> allowance_miscellaneous { get; set; }
        public Nullable<double> total_allowance_basic { get; set; }
        public Nullable<double> allowance_ticket { get; set; }
        public Nullable<double> allowance_visa { get; set; }
        public Nullable<double> allowance_passport { get; set; }
        public Nullable<double> total_allowance_document { get; set; }
        public Nullable<double> grand_total_allowance { get; set; }
        public string destination_1 { get; set; }
        public Nullable<System.DateTime> startDate_1 { get; set; }
        public Nullable<System.DateTime> endDate_1 { get; set; }
        public Nullable<int> duration_1 { get; set; }
        public string destination_2 { get; set; }
        public Nullable<System.DateTime> startDate_2 { get; set; }
        public Nullable<System.DateTime> endDate_2 { get; set; }
        public Nullable<int> duration_2 { get; set; }
        public string destination_3 { get; set; }
        public Nullable<System.DateTime> startDate_3 { get; set; }
        public Nullable<System.DateTime> endDate_3 { get; set; }
        public Nullable<int> duration_3 { get; set; }
        public string destination_4 { get; set; }
        public Nullable<System.DateTime> startDate_4 { get; set; }
        public Nullable<System.DateTime> endDate_4 { get; set; }
        public Nullable<int> duration_4 { get; set; }
        public string destination_5 { get; set; }
        public Nullable<System.DateTime> startDate_5 { get; set; }
        public Nullable<System.DateTime> endDate_5 { get; set; }
        public Nullable<int> duration_5 { get; set; }
        public string destination_6 { get; set; }
        public Nullable<System.DateTime> startDate_6 { get; set; }
        public Nullable<System.DateTime> endDate_6 { get; set; }
        public Nullable<int> duration_6 { get; set; }
        public string status_request { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<bool> active_flag { get; set; }
        public int rank_id { get; set; }
        public Nullable<int> apprv_by_lvl6 { get; set; }
        public Nullable<int> apprv_by_lvl7 { get; set; }
        public Nullable<int> apprv_by_lvl8 { get; set; }
        public Nullable<int> apprv_by_lvl9 { get; set; }
        public Nullable<int> apprv_by_lvl10 { get; set; }
        public Nullable<int> apprv_by_lvl11 { get; set; }
        public Nullable<int> apprv_by_lvl12 { get; set; }
        public Nullable<int> apprv_by_lvl13 { get; set; }
        public Nullable<int> apprv_by_lvl14 { get; set; }
        public Nullable<int> apprv_by_lvl15 { get; set; }
        public Nullable<int> apprv_by_lvl16 { get; set; }
        public Nullable<int> apprv_by_lvl17 { get; set; }
        public Nullable<int> apprv_by_lvl18 { get; set; }
        public Nullable<int> apprv_by_lvl19 { get; set; }
        public Nullable<int> apprv_by_lvl20 { get; set; }
        public string apprv_flag_lvl6 { get; set; }
        public string apprv_flag_lvl7 { get; set; }
        public string apprv_flag_lvl8 { get; set; }
        public string apprv_flag_lvl9 { get; set; }
        public string apprv_flag_lvl10 { get; set; }
        public string apprv_flag_lvl11 { get; set; }
        public string apprv_flag_lvl12 { get; set; }
        public string apprv_flag_lvl13 { get; set; }
        public string apprv_flag_lvl14 { get; set; }
        public string apprv_flag_lvl15 { get; set; }
        public string apprv_flag_lvl16 { get; set; }
        public string apprv_flag_lvl17 { get; set; }
        public string apprv_flag_lvl18 { get; set; }
        public string apprv_flag_lvl19 { get; set; }
        public string apprv_flag_lvl20 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl6 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl7 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl8 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl9 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl10 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl11 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl12 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl13 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl14 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl15 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl16 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl17 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl18 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl19 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl20 { get; set; }
    }
}
