//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_travel_profile
    {
        public string group_code { get; set; }
        public int id_request { get; set; }
        public string unit_code { get; set; }
        public Nullable<int> no_reg { get; set; }
        public Nullable<int> id_destination_city { get; set; }
        public Nullable<int> destination_code { get; set; }
        public Nullable<bool> participants_flag { get; set; }
        public Nullable<int> invited_by { get; set; }
        public Nullable<bool> overseas_flag { get; set; }
        public Nullable<bool> request_type { get; set; }
        public string travel_purpose { get; set; }
        public Nullable<bool> air_ticket_flag { get; set; }
        public Nullable<bool> passport_flag { get; set; }
        public Nullable<int> apprv_by_lvl1 { get; set; }
        public Nullable<int> apprv_by_lvl2 { get; set; }
        public Nullable<int> apprv_by_lvl3 { get; set; }
        public Nullable<int> apprv_by_lvl4 { get; set; }
        public Nullable<int> apprv_by_lvl5 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl1 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl2 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl3 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl4 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl5 { get; set; }
        public Nullable<double> budget { get; set; }
        public Nullable<bool> exep_empolyee { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string comments { get; set; }
        public Nullable<double> transit_by_land { get; set; }
        public Nullable<double> transit_by_air { get; set; }
        public Nullable<double> total_transit { get; set; }
        public Nullable<double> allowance_transit_by_land { get; set; }
        public Nullable<double> allowance_transit_by_air { get; set; }
        public Nullable<double> total_allowance_transit { get; set; }
        public Nullable<double> allowance_meal_idr { get; set; }
        public Nullable<double> allowance_hotel { get; set; }
        public Nullable<double> allowance_transportation { get; set; }
        public Nullable<double> allowance_laundry { get; set; }
        public Nullable<double> allowance_miscellaneous { get; set; }
        public Nullable<double> total_allowance_basic { get; set; }
        public Nullable<double> allowance_ticket { get; set; }
        public Nullable<double> allowance_visa { get; set; }
        public Nullable<double> allowance_passport { get; set; }
        public Nullable<double> total_allowance_document { get; set; }
        public Nullable<double> grand_total_allowance { get; set; }
        public Nullable<bool> active_flag { get; set; }
        public Nullable<int> diff_day { get; set; }
        public string approriate_status { get; set; }
        public string division_name { get; set; }
        public Nullable<int> apprv_by_lvl6 { get; set; }
        public Nullable<int> apprv_by_lvl7 { get; set; }
        public Nullable<int> apprv_by_lvl8 { get; set; }
        public Nullable<int> apprv_by_lvl9 { get; set; }
        public Nullable<int> apprv_by_lvl10 { get; set; }
        public Nullable<int> apprv_by_lvl11 { get; set; }
        public Nullable<int> apprv_by_lvl12 { get; set; }
        public Nullable<int> apprv_by_lvl13 { get; set; }
        public Nullable<int> apprv_by_lvl14 { get; set; }
        public Nullable<int> apprv_by_lvl15 { get; set; }
        public Nullable<int> apprv_by_lvl16 { get; set; }
        public Nullable<int> apprv_by_lvl17 { get; set; }
        public Nullable<int> apprv_by_lvl18 { get; set; }
        public Nullable<int> apprv_by_lvl19 { get; set; }
        public Nullable<int> apprv_by_lvl20 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl6 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl7 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl8 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl9 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl10 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl11 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl12 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl13 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl14 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl15 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl16 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl17 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl18 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl19 { get; set; }
        public Nullable<System.DateTime> apprv_date_lvl20 { get; set; }
    }
}
