//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_travel_allowance
    {
        public string @class { get; set; }
        public int id_travel_procedures { get; set; }
        public Nullable<short> id_region { get; set; }
        public string destination_type { get; set; }
        public Nullable<double> meal_allowance { get; set; }
        public Nullable<double> pre_allowance_1_to_14_day { get; set; }
        public Nullable<double> pre_allowance_15_to_90_day { get; set; }
        public Nullable<double> pre_allowance_90_more { get; set; }
        public Nullable<double> winter_allowance { get; set; }
        public string land_transport { get; set; }
    }
}
