//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONTRAST_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_total_budget
    {
        public Nullable<System.DateTime> date_id { get; set; }
        public string division_name { get; set; }
        public Nullable<bool> request_type { get; set; }
        public Nullable<bool> overseas_flag { get; set; }
        public Nullable<int> count_req { get; set; }
        public int total_ticket { get; set; }
        public int total_hotel { get; set; }
        public Nullable<int> actual_cost { get; set; }
        public int total_meal { get; set; }
        public int total_winter { get; set; }
        public int total_preparation { get; set; }
        public int total_laundry { get; set; }
        public int total_miscellaneous { get; set; }
        public int total_transportation { get; set; }
        public Nullable<int> grand_total_settlement { get; set; }
    }
}
